llm:
  remote:
    - name: OpenaiRemote
      service: openai-official
      key: sk-123456
    - name: OtherCGPTRemote
      url: "https://example.com"
      service: openai
      key: sk-098765
    - name: ModLLMRemote
      url: "https://example.com"
      key: abc
      adapter: default

tts:
  enable: false
  remote:
    - name:
im:
  remote:
    - name: QQChannel
      adapter: qch
      appid: abcdef
      token: fedcba
      ws_port: 8060
      http_port: 8080
      host: localhost
    - name: mirai-api-http
      adapter: mah
      appid: abcdef
      token: fedcba
      ws_port: 8060
      http_port: 8080
      host: localhost